# Generated by Django 4.1.2 on 2022-10-07 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Room Name')),
                ('entry_user', models.CharField(blank=True, max_length=120, verbose_name='entry_user')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('subject', models.CharField(max_length=120, verbose_name='subject')),
                ('entry_user', models.CharField(blank=True, max_length=120, verbose_name='entry_user')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(blank=True, max_length=120, verbose_name='From_to_To')),
                ('entry_user', models.CharField(blank=True, max_length=120, verbose_name='entry_user')),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='Schedule Date')),
                ('teacher_name_subject', models.CharField(max_length=120, null=True, verbose_name='Teacher')),
                ('time_slot', models.CharField(max_length=120, null=True, verbose_name='TimeSlot')),
                ('room_name', models.CharField(max_length=120, null=True, verbose_name='Room')),
                ('entry_user', models.CharField(max_length=120, verbose_name='entry_user')),
            ],
        ),
    ]
