# Generated by Django 4.1.2 on 2022-10-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
    ]
