# Generated by Django 4.1.2 on 2022-10-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_scheduler', '0004_rename_upload_uploadfile_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalHoldTimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='Schedule Date')),
                ('teacher_name_subject', models.CharField(max_length=120, null=True, verbose_name='Teacher')),
                ('time_slot', models.CharField(max_length=120, null=True, verbose_name='TimeSlot')),
                ('room_name', models.CharField(max_length=120, null=True, verbose_name='Room')),
                ('entry_user', models.CharField(max_length=120, verbose_name='entry_user')),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryHoldTimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='Schedule Date')),
                ('teacher_name_subject', models.CharField(max_length=120, null=True, verbose_name='Teacher')),
                ('time_slot', models.CharField(max_length=120, null=True, verbose_name='TimeSlot')),
                ('room_name', models.CharField(max_length=120, null=True, verbose_name='Room')),
                ('entry_user', models.CharField(max_length=120, verbose_name='entry_user')),
            ],
        ),
    ]
