# Generated by Django 4.1.2 on 2022-10-08 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_scheduler', '0005_finalholdtimetable_temporaryholdtimetable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporaryholdtimetable',
            name='room_name',
        ),
    ]
